#include "frontend/token_kind.h"

#include <stddef.h>

#include "util/macro_util.h"

const char* get_token_kind_spelling(enum token_kind kind) {
    switch (kind) {
        case TOKEN_FUNC_NAME:
            return "__func__";
        case TOKEN_SIZEOF:
            return "sizeof";
        case TOKEN_PTR_OP:
            return "->";
        case TOKEN_INC:
            return "++";
        case TOKEN_DEC:
            return "--";
        case TOKEN_LSHIFT:
            return "<<";
        case TOKEN_RSHIFT:
            return ">>";
        case TOKEN_LE:
            return "<=";
        case TOKEN_GE:
            return ">=";
        case TOKEN_EQ:
            return "==";
        case TOKEN_NE:
            return "!=";
        case TOKEN_LAND:
            return "&&";
        case TOKEN_LOR:
            return "||";
        case TOKEN_MUL_ASSIGN:
            return "*=";
        case TOKEN_DIV_ASSIGN:
            return "/=";
        case TOKEN_MOD_ASSIGN:
            return "%=";
        case TOKEN_ADD_ASSIGN:
            return "+=";
        case TOKEN_SUB_ASSIGN:
            return "-=";
        case TOKEN_LSHIFT_ASSIGN:
            return "<<=";
        case TOKEN_RSHIFT_ASSIGN:
            return ">>=";
        case TOKEN_AND_ASSIGN:
            return "&=";
        case TOKEN_OR_ASSIGN:
            return "|=";
        case TOKEN_XOR_ASSIGN:
            return "^=";
        case TOKEN_TYPEDEF:
            return "typedef";
        case TOKEN_EXTERN:
            return "extern";
        case TOKEN_STATIC:
            return "static";
        case TOKEN_AUTO:
            return "auto";
        case TOKEN_REGISTER:
            return "register";
        case TOKEN_INLINE:
            return "inline";
        case TOKEN_BOOL:
            return "_Bool";
        case TOKEN_CHAR:
            return "char";
        case TOKEN_SHORT:
            return "short";
        case TOKEN_INT:
            return "int";
        case TOKEN_LONG:
            return "long";
        case TOKEN_SIGNED:
            return "signed";
        case TOKEN_UNSIGNED:
            return "unsigned";
        case TOKEN_FLOAT:
            return "float";
        case TOKEN_DOUBLE:
            return "double";
        case TOKEN_VOID:
            return "void";
        case TOKEN_COMPLEX:
            return "_Complex";
        case TOKEN_IMAGINARY:
            return "_Imaginary";
        case TOKEN_CONST:
            return "const";
        case TOKEN_VOLATILE:
            return "volatile";
        case TOKEN_RESTRICT:
            return "restrict";
        case TOKEN_ATOMIC:
            return "_Atomic";
        case TOKEN_STRUCT:
            return "struct";
        case TOKEN_UNION:
            return "union";
        case TOKEN_ENUM:
            return "enum";
        case TOKEN_ELLIPSIS:
            return "...";
        case TOKEN_CASE:
            return "case";
        case TOKEN_DEFAULT:
            return "default";
        case TOKEN_IF:
            return "if";
        case TOKEN_ELSE:
            return "else";
        case TOKEN_SWITCH:
            return "switch";
        case TOKEN_WHILE:
            return "while";
        case TOKEN_DO:
            return "do";
        case TOKEN_FOR:
            return "for";
        case TOKEN_GOTO:
            return "goto";
        case TOKEN_CONTINUE:
            return "continue";
        case TOKEN_BREAK:
            return "break";
        case TOKEN_RETURN:
            return "return";
        case TOKEN_ALIGNAS:
            return "_Alignas";
        case TOKEN_ALIGNOF:
            return "_Alignof";
        case TOKEN_GENERIC:
            return "_Generic";
        case TOKEN_NORETURN:
            return "_Noreturn";
        case TOKEN_STATIC_ASSERT:
            return "_Static_assert";
        case TOKEN_THREAD_LOCAL:
            return "_Thread_local";
        case TOKEN_SEMICOLON:
            return ";";
        case TOKEN_LBRACKET:
            return "(";
        case TOKEN_RBRACKET:
            return ")";
        case TOKEN_LBRACE:
            return "{";
        case TOKEN_RBRACE:
            return "}";
        case TOKEN_LINDEX:
            return "[";
        case TOKEN_RINDEX:
            return "]";
        case TOKEN_DOT:
            return ".";
        case TOKEN_AND:
            return "&";
        case TOKEN_OR:
            return "|";
        case TOKEN_XOR:
            return "^";
        case TOKEN_NOT:
            return "!";
        case TOKEN_BNOT:
            return "~";
        case TOKEN_SUB:
            return "-";
        case TOKEN_ADD:
            return "+";
        case TOKEN_ASTERISK:
            return "*";
        case TOKEN_DIV:
            return "/";
        case TOKEN_MOD:
            return "%";
        case TOKEN_LT:
            return "<";
        case TOKEN_GT:
            return ">";
        case TOKEN_QMARK:
            return "?";
        case TOKEN_COLON:
            return ":";
        case TOKEN_ASSIGN:
            return "=";
        case TOKEN_COMMA:
            return ",";
        case TOKEN_PP_STRINGIFY:
            return "#";
        case TOKEN_PP_CONCAT:
            return "##";

        default:
            return NULL;
    }
}

const char* get_token_kind_str(enum token_kind kind) {
    switch (kind) {
        case TOKEN_IDENTIFIER:
            return "IDENTIFIER";
        case TOKEN_I_CONSTANT:
            return "I_CONSTANT";
        case TOKEN_F_CONSTANT:
            return "F_CONSTANT";
        case TOKEN_STRING_LITERAL:
            return "STRING_LITERAL";
        case TOKEN_TYPEDEF_NAME:
            return "TYPEDEF_NAME";
        case TOKEN_FUNC_NAME:
            return "FUNC_NAME";
        case TOKEN_SIZEOF:
            return "SIZEOF";
        case TOKEN_PTR_OP:
            return "PTR_OP";
        case TOKEN_INC:
            return "INC_OP";
        case TOKEN_DEC:
            return "DEC_OP";
        case TOKEN_LSHIFT:
            return "LEFT_OP";
        case TOKEN_RSHIFT:
            return "RIGHT_OP";
        case TOKEN_LE:
            return "LE_OP";
        case TOKEN_GE:
            return "GE_OP";
        case TOKEN_EQ:
            return "EQ_OP";
        case TOKEN_NE:
            return "NE_OP";
        case TOKEN_LAND:
            return "AND_OP";
        case TOKEN_LOR:
            return "OR_OP";
        case TOKEN_MUL_ASSIGN:
            return "MUL_ASSIGN";
        case TOKEN_DIV_ASSIGN:
            return "DIV_ASSIGN";
        case TOKEN_MOD_ASSIGN:
            return "MOD_ASSIGN";
        case TOKEN_ADD_ASSIGN:
            return "ADD_ASSIGN";
        case TOKEN_SUB_ASSIGN:
            return "SUB_ASSIGN";
        case TOKEN_LSHIFT_ASSIGN:
            return "LEFT_ASSIGN";
        case TOKEN_RSHIFT_ASSIGN:
            return "RIGHT_ASSIGN";
        case TOKEN_AND_ASSIGN:
            return "AND_ASSIGN";
        case TOKEN_OR_ASSIGN:
            return "OR_ASSIGN";
        case TOKEN_XOR_ASSIGN:
            return "XOR_ASSIGN";
        case TOKEN_TYPEDEF:
            return "TYPEDEF";
        case TOKEN_EXTERN:
            return "EXTERN";
        case TOKEN_STATIC:
            return "STATIC";
        case TOKEN_AUTO:
            return "AUTO";
        case TOKEN_REGISTER:
            return "REGISTER";
        case TOKEN_INLINE:
            return "INLINE";
        case TOKEN_BOOL:
            return "BOOL";
        case TOKEN_CHAR:
            return "CHAR";
        case TOKEN_SHORT:
            return "SHORT";
        case TOKEN_INT:
            return "INT";
        case TOKEN_LONG:
            return "LONG";
        case TOKEN_SIGNED:
            return "SIGNED";
        case TOKEN_UNSIGNED:
            return "UNSIGNED";
        case TOKEN_FLOAT:
            return "FLOAT";
        case TOKEN_DOUBLE:
            return "DOUBLE";
        case TOKEN_VOID:
            return "VOID";
        case TOKEN_COMPLEX:
            return "COMPLEX";
        case TOKEN_IMAGINARY:
            return "IMAGINARY";
        case TOKEN_CONST:
            return "CONST";
        case TOKEN_VOLATILE:
            return "VOLATILE";
        case TOKEN_RESTRICT:
            return "RESTRICT";
        case TOKEN_ATOMIC:
            return "ATOMIC";
        case TOKEN_STRUCT:
            return "STRUCT";
        case TOKEN_UNION:
            return "UNION";
        case TOKEN_ENUM:
            return "ENUM";
        case TOKEN_ELLIPSIS:
            return "ELLIPSIS";
        case TOKEN_CASE:
            return "CASE";
        case TOKEN_DEFAULT:
            return "DEFAULT";
        case TOKEN_IF:
            return "IF";
        case TOKEN_ELSE:
            return "ELSE";
        case TOKEN_SWITCH:
            return "SWITCH";
        case TOKEN_WHILE:
            return "WHILE";
        case TOKEN_DO:
            return "DO";
        case TOKEN_FOR:
            return "FOR";
        case TOKEN_GOTO:
            return "GOTO";
        case TOKEN_CONTINUE:
            return "CONTINUE";
        case TOKEN_BREAK:
            return "BREAK";
        case TOKEN_RETURN:
            return "RETURN";
        case TOKEN_ALIGNAS:
            return "ALIGNAS";
        case TOKEN_ALIGNOF:
            return "ALIGNOF";
        case TOKEN_GENERIC:
            return "GENERIC";
        case TOKEN_NORETURN:
            return "NORETURN";
        case TOKEN_STATIC_ASSERT:
            return "STATIC_ASSERT";
        case TOKEN_THREAD_LOCAL:
            return "THREAD_LOCAL";
        case TOKEN_SEMICOLON:
            return "SEMICOLON";
        case TOKEN_LBRACKET:
            return "LBRACKET";
        case TOKEN_RBRACKET:
            return "RBRACKET";
        case TOKEN_LBRACE:
            return "LBRACE";
        case TOKEN_RBRACE:
            return "RBRACE";
        case TOKEN_LINDEX:
            return "LINDEX";
        case TOKEN_RINDEX:
            return "RINDEX";
        case TOKEN_DOT:
            return "DOT";
        case TOKEN_AND:
            return "AND";
        case TOKEN_OR:
            return "OR";
        case TOKEN_XOR:
            return "XOR";
        case TOKEN_NOT:
            return "NOT";
        case TOKEN_BNOT:
            return "BNOT";
        case TOKEN_SUB:
            return "SUB";
        case TOKEN_ADD:
            return "ADD";
        case TOKEN_ASTERISK:
            return "ASTERISK";
        case TOKEN_DIV:
            return "DIV";
        case TOKEN_MOD:
            return "MOD";
        case TOKEN_LT:
            return "LT";
        case TOKEN_GT:
            return "GT";
        case TOKEN_QMARK:
            return "QMARK";
        case TOKEN_COLON:
            return "COLON";
        case TOKEN_ASSIGN:
            return "ASSIGN";
        case TOKEN_COMMA:
            return "COMMA";
        case TOKEN_PP_STRINGIFY:
            return "STRINGIFY_OP";
        case TOKEN_PP_CONCAT:
            return "CONCAT_OP";
        case TOKEN_INVALID:
            return "INVALID";
    }
    return NULL;
}

